language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
