name: Checks

on: [pull_request, push]

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - run: yarn install
      - run: yarn build
      - run: yarn check-types
      - run: yarn lint
